### PR TITLE
Update dependencies and README for Robolectric 4.8

### PR DESCRIPTION
**Pull request by utzcoz**
See https://github.com/robolectric/robolectric/releases/tag/robolectric-4.8

### CODE REVIEW

**Comment by utzcoz** [comment]
I need to update other dependencies sha256 for v4.

**Comment by utzcoz** [comment]
> I need to update other dependencies sha256 for v4.

All dependencies updated. @hoisie @JuliaSullivanGoogle What about adding a task to generate those dependencies rules for robolectric-bazel from Robolectric main repository?

**Review by Bencodes — APPROVED** [review]

**Comment by Bencodes** [comment]
There's a 4.8.1 release that just got cut as well. If you merge this in, we can cut a quick release for 4.8, and follow with a second release cut for 4.8.1.

**Comment by utzcoz** [comment]
> There's a 4.8.1 release that just got cut as well. If you merge this in, we can cut a quick release for 4.8, and follow with a second release cut for 4.8.1.

Thanks for reviewing. IMO, we should keep robolectric-bazel's version the same as Robolectric. We can merge it firstly and release 4.8 for robolectric-bazel, and send new PR for 4.8.1. I remember @brettchabot propose this rule for version consistency at previous PR discussion page.

**Pull request merged**
