### PR TITLE
Add 4.9-alpha-1 support

### PR DESCRIPTION
**Pull request by Bencodes**

### CODE REVIEW

**Comment by utzcoz** [comment]
@Bencodes  @brettchabot  do we need to support alpha prerelease?

**Comment by utzcoz** [comment]
@Bencodes We can move on for Robolectric 4.9 now. The stable version is released.

**Comment by Bencodes** [comment]
@utzcoz opened a new PR over here if you want to have a look https://github.com/robolectric/robolectric-bazel/pull/35

**Comment by utzcoz** [comment]
@Bencodes We can merge this one, and then update https://github.com/robolectric/robolectric-bazel/pull/35 for stable 4.9 release.

**Review by utzcoz — APPROVED** [review]

**Pull request merged**
